### ISSUE TITLE
Stripe   Error  Authentication

### ISSUE THREAD

**Issue by amjadalibalti123** [amdtllc/sbms#2]
when i add user i faced this problem
Stripe \ Error \ Authentication
No API key provided. (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.

 please resolve this problem.

**Comment by jgmuchiri** [comment]
Did you copy .env.example to .env and update the Stripe API keys accordingly?
![image](https://user-images.githubusercontent.com/4142133/36392889-62beb054-157b-11e8-9f98-3549ff6591e5.png)

**Comment by amjadalibalti123** [comment]
Yes i changed...

**Comment by jgmuchiri** [comment]
That error indicates an issue with your API keys  authorizing with Stripe. I just tested user creation and it works on my end. What is the URL on the page that throws that error? Can you show a dump of the log file (settings>debug log) or http://<your-installation-url>/debug-log

Your stripe settings should look like the following
```
STRIPE_TEST_SECRET=sk_test_xxxxxxx
or 
STRIPE_TEST_SECRET='sk_test_xxxxxxx'
```
